### ISSUE TITLE
이슈vim(빔)

### ISSUE THREAD

**Issue by KiRist-code** [Mireu-Labcon/Golang-Edu#1]
![New Project](https://user-images.githubusercontent.com/37296174/119231749-6a050a80-bb5d-11eb-9eb7-c1625d757661.png)
이슈라 쓰고 콧코로라 읽는다

**Comment by Mireu-Labcon** [comment]
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by gunyu1019** [comment]
![image](https://user-images.githubusercontent.com/16767890/119231820-a46ea780-bb5d-11eb-8da1-d35813ae2a89.png)

**Comment by gunyu1019** [comment]
재오픈 쌉가능?

**Comment by KiRist-code** [comment]
닫지마

**Comment by Mireu-Labcon** [comment]
다른데있음

**Comment by Mireu-Labcon** [comment]
``https://github.com/Mireu-Labcon/Golang-Edu/issues/2``
